/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyPendingRouteImport } from './routes/verify-pending'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog/index'
import { Route as AuthenticatedCatalogCategoriesRouteImport } from './routes/_authenticated/catalog/categories'
import { Route as AuthenticatedHouseholdsHouseholdIdRouteImport } from './routes/_authenticated/households/$householdId'
import { Route as AuthenticatedJoinTokenRouteImport } from './routes/_authenticated/join/$token'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists/index'
import { Route as AuthenticatedListsListIdIndexRouteImport } from './routes/_authenticated/lists/$listId/index'
import { Route as AuthenticatedListsListIdHistoryRouteImport } from './routes/_authenticated/lists/$listId/history'
import { Route as AuthenticatedListsListIdShopRouteImport } from './routes/_authenticated/lists/$listId/shop'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPendingRoute = VerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesRoute =
  AuthenticatedCatalogCategoriesRouteImport.update({
    id: '/catalog/categories',
    path: '/catalog/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdRoute =
  AuthenticatedHouseholdsHouseholdIdRouteImport.update({
    id: '/households/$householdId',
    path: '/households/$householdId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJoinTokenRoute = AuthenticatedJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListsListIdIndexRoute =
  AuthenticatedListsListIdIndexRouteImport.update({
    id: '/lists/$listId/',
    path: '/lists/$listId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListsListIdHistoryRoute =
  AuthenticatedListsListIdHistoryRouteImport.update({
    id: '/lists/$listId/history',
    path: '/lists/$listId/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListsListIdShopRoute =
  AuthenticatedListsListIdShopRouteImport.update({
    id: '/lists/$listId/shop',
    path: '/lists/$listId/shop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/register': typeof GuestRegisterRoute
  '/sign-in': typeof GuestSignInRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesRoute
  '/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRoute
  '/join/$token': typeof AuthenticatedJoinTokenRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/lists/': typeof AuthenticatedListsIndexRoute
  '/lists/$listId/history': typeof AuthenticatedListsListIdHistoryRoute
  '/lists/$listId/shop': typeof AuthenticatedListsListIdShopRoute
  '/lists/$listId/': typeof AuthenticatedListsListIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/register': typeof GuestRegisterRoute
  '/sign-in': typeof GuestSignInRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesRoute
  '/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRoute
  '/join/$token': typeof AuthenticatedJoinTokenRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/lists/$listId/history': typeof AuthenticatedListsListIdHistoryRoute
  '/lists/$listId/shop': typeof AuthenticatedListsListIdShopRoute
  '/lists/$listId': typeof AuthenticatedListsListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catalog/categories': typeof AuthenticatedCatalogCategoriesRoute
  '/_authenticated/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRoute
  '/_authenticated/join/$token': typeof AuthenticatedJoinTokenRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
  '/_authenticated/lists/$listId/history': typeof AuthenticatedListsListIdHistoryRoute
  '/_authenticated/lists/$listId/shop': typeof AuthenticatedListsListIdShopRoute
  '/_authenticated/lists/$listId/': typeof AuthenticatedListsListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/verify-email'
    | '/verify-pending'
    | '/profile'
    | '/forgot-password'
    | '/register'
    | '/sign-in'
    | '/catalog/categories'
    | '/households/$householdId'
    | '/join/$token'
    | '/catalog/'
    | '/lists/'
    | '/lists/$listId/history'
    | '/lists/$listId/shop'
    | '/lists/$listId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/verify-email'
    | '/verify-pending'
    | '/profile'
    | '/forgot-password'
    | '/register'
    | '/sign-in'
    | '/catalog/categories'
    | '/households/$householdId'
    | '/join/$token'
    | '/catalog'
    | '/lists'
    | '/lists/$listId/history'
    | '/lists/$listId/shop'
    | '/lists/$listId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/reset-password'
    | '/verify-email'
    | '/verify-pending'
    | '/_authenticated/profile'
    | '/_guest/forgot-password'
    | '/_guest/register'
    | '/_guest/sign-in'
    | '/_authenticated/'
    | '/_authenticated/catalog/categories'
    | '/_authenticated/households/$householdId'
    | '/_authenticated/join/$token'
    | '/_authenticated/catalog/'
    | '/_authenticated/lists/'
    | '/_authenticated/lists/$listId/history'
    | '/_authenticated/lists/$listId/shop'
    | '/_authenticated/lists/$listId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyPendingRoute: typeof VerifyPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-pending': {
      id: '/verify-pending'
      path: '/verify-pending'
      fullPath: '/verify-pending'
      preLoaderRoute: typeof VerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories': {
      id: '/_authenticated/catalog/categories'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/$householdId': {
      id: '/_authenticated/households/$householdId'
      path: '/households/$householdId'
      fullPath: '/households/$householdId'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join/$token': {
      id: '/_authenticated/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AuthenticatedJoinTokenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/$listId/': {
      id: '/_authenticated/lists/$listId/'
      path: '/lists/$listId'
      fullPath: '/lists/$listId/'
      preLoaderRoute: typeof AuthenticatedListsListIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/$listId/history': {
      id: '/_authenticated/lists/$listId/history'
      path: '/lists/$listId/history'
      fullPath: '/lists/$listId/history'
      preLoaderRoute: typeof AuthenticatedListsListIdHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/$listId/shop': {
      id: '/_authenticated/lists/$listId/shop'
      path: '/lists/$listId/shop'
      fullPath: '/lists/$listId/shop'
      preLoaderRoute: typeof AuthenticatedListsListIdShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogCategoriesRoute: typeof AuthenticatedCatalogCategoriesRoute
  AuthenticatedHouseholdsHouseholdIdRoute: typeof AuthenticatedHouseholdsHouseholdIdRoute
  AuthenticatedJoinTokenRoute: typeof AuthenticatedJoinTokenRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
  AuthenticatedListsListIdHistoryRoute: typeof AuthenticatedListsListIdHistoryRoute
  AuthenticatedListsListIdShopRoute: typeof AuthenticatedListsListIdShopRoute
  AuthenticatedListsListIdIndexRoute: typeof AuthenticatedListsListIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogCategoriesRoute: AuthenticatedCatalogCategoriesRoute,
  AuthenticatedHouseholdsHouseholdIdRoute:
    AuthenticatedHouseholdsHouseholdIdRoute,
  AuthenticatedJoinTokenRoute: AuthenticatedJoinTokenRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
  AuthenticatedListsListIdHistoryRoute: AuthenticatedListsListIdHistoryRoute,
  AuthenticatedListsListIdShopRoute: AuthenticatedListsListIdShopRoute,
  AuthenticatedListsListIdIndexRoute: AuthenticatedListsListIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestSignInRoute: typeof GuestSignInRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestSignInRoute: GuestSignInRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyPendingRoute: VerifyPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
