import type { IconKey } from '@shoppy/shared';
import {
  Apple,
  Baby,
  Banana,
  Bean,
  Beef,
  Beer,
  Book,
  CakeSlice,
  Candy,
  Carrot,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Drumstick,
  Dumbbell,
  Egg,
  Fish,
  Flower2,
  Gift,
  GlassWater,
  Grape,
  Ham,
  Heart,
  House,
  IceCreamCone,
  LeafyGreen,
  Lightbulb,
  type LucideIcon,
  Milk,
  Nut,
  Package,
  PartyPopper,
  PawPrint,
  Pencil,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Salad,
  Sandwich,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Snowflake,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  Star,
  Store,
  Sun,
  Tag,
  Tent,
  TreePine,
  Utensils,
  Wheat,
  Wine,
  Wrench,
} from 'lucide-react';

export const ICON_COMPONENTS: Record<IconKey, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  'shopping-basket': ShoppingBasket,
  'shopping-bag': ShoppingBag,
  store: Store,
  apple: Apple,
  banana: Banana,
  carrot: Carrot,
  cherry: Cherry,
  citrus: Citrus,
  grape: Grape,
  salad: Salad,
  'leafy-green': LeafyGreen,
  croissant: Croissant,
  sandwich: Sandwich,
  'cake-slice': CakeSlice,
  cookie: Cookie,
  milk: Milk,
  egg: Egg,
  beef: Beef,
  drumstick: Drumstick,
  fish: Fish,
  ham: Ham,
  wheat: Wheat,
  bean: Bean,
  nut: Nut,
  pizza: Pizza,
  soup: Soup,
  popcorn: Popcorn,
  candy: Candy,
  'ice-cream-cone': IceCreamCone,
  snowflake: Snowflake,
  'cup-soda': CupSoda,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  'glass-water': GlassWater,
  utensils: Utensils,
  'cooking-pot': CookingPot,
  'spray-can': SprayCan,
  sparkles: Sparkles,
  'shower-head': ShowerHead,
  pill: Pill,
  baby: Baby,
  'paw-print': PawPrint,
  shirt: Shirt,
  gift: Gift,
  house: House,
  wrench: Wrench,
  lightbulb: Lightbulb,
  package: Package,
  sprout: Sprout,
  'flower-2': Flower2,
  tag: Tag,
  star: Star,
  heart: Heart,
  'party-popper': PartyPopper,
  'tree-pine': TreePine,
  sun: Sun,
  tent: Tent,
  plane: Plane,
  dumbbell: Dumbbell,
  book: Book,
  pencil: Pencil,
};
