import { z } from 'zod';

// Curated Lucide icon keys for categories and lists (D-14). The web app maps each key to a component.
export const ICON_KEYS = [
  'shopping-cart',
  'shopping-basket',
  'shopping-bag',
  'store',
  'apple',
  'banana',
  'carrot',
  'cherry',
  'citrus',
  'grape',
  'salad',
  'leafy-green',
  'croissant',
  'sandwich',
  'cake-slice',
  'cookie',
  'milk',
  'egg',
  'beef',
  'drumstick',
  'fish',
  'ham',
  'wheat',
  'bean',
  'nut',
  'pizza',
  'soup',
  'popcorn',
  'candy',
  'ice-cream-cone',
  'snowflake',
  'cup-soda',
  'coffee',
  'wine',
  'beer',
  'glass-water',
  'utensils',
  'cooking-pot',
  'spray-can',
  'sparkles',
  'shower-head',
  'pill',
  'baby',
  'paw-print',
  'shirt',
  'gift',
  'house',
  'wrench',
  'lightbulb',
  'package',
  'sprout',
  'flower-2',
  'tag',
  'star',
  'heart',
  'party-popper',
  'tree-pine',
  'sun',
  'tent',
  'plane',
  'dumbbell',
  'book',
  'pencil',
] as const;

export const iconKeySchema = z.enum(ICON_KEYS, 'Pick an icon');
export type IconKey = z.infer<typeof iconKeySchema>;

export const DEFAULT_LIST_ICON: IconKey = 'shopping-cart';
